# Generated by Django 4.2.6 on 2023-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogAcc', '0002_alter_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('leader', 'Team Leader')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
