# Generated by Django 4.2.5 on 2023-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogAcc', '0002_alter_budget_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
