# Generated by Django 4.2.5 on 2023-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogAcc', '0003_alter_budget_monthly_limit_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
