# Generated by Django 4.2.5 on 2023-09-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogAcc', '0004_budget_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'permissions': [('can_toggle_lock', 'Can toggle lock status')]},
        ),
    ]
