# Generated by Django 4.2.5 on 2024-04-07 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogAcc', '0004_budget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='team',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.AddField(
            model_name='budget',
            name='team',
            field=models.ManyToManyField(to='LogAcc.team'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
