# Generated by Django 4.2.5 on 2024-04-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogAcc', '0005_remove_budget_team_remove_budget_user_budget_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='team',
        ),
        migrations.AddField(
            model_name='budget',
            name='team',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='LogAcc.team'),
            preserve_default=False,
        ),
    ]
